MSP430 Peripheral Driver Library: pmm.c File Reference
pmm.c File Reference
#include "inc/hw_types.h"
#include "driverlib/5xx_6xx/debug.h"
#include "driverlib/5xx_6xx/pmm.h"
#include "msp430xgeneric.h"
Functions
void PMM_enableSvsL (unsigned int baseAddress)
void PMM_disableSvsL (unsigned int baseAddress)
void PMM_enableSvmL (unsigned int baseAddress)
void PMM_disableSvmL (unsigned int baseAddress)
void PMM_enableSvsH (unsigned int baseAddress)
void PMM_disableSvsH (unsigned int baseAddress)
void PMM_enableSvmH (unsigned int baseAddress)
void PMM_disableSvmH (unsigned int baseAddress)
void PMM_enableSvsLSvmL (unsigned int baseAddress)
void PMM_disableSvsLSvmL (unsigned int baseAddress)
void PMM_enableSvsHSvmH (unsigned int baseAddress)
void PMM_disableSvsHSvmH (unsigned int baseAddress)
void PMM_enableSvsLReset (unsigned int baseAddress)
void PMM_disableSvsLReset (unsigned int baseAddress)
void PMM_enableSvmLInterrupt (unsigned int baseAddress)
void PMM_disableSvmLInterrupt (unsigned int baseAddress)
void PMM_enableSvsHReset (unsigned int baseAddress)
void PMM_disableSvsHReset (unsigned int baseAddress)
void PMM_enableSvmHInterrupt (unsigned int baseAddress)
void PMM_disableSvmHInterrupt (unsigned int baseAddress)
void PMM_clearPMMIFGS (unsigned int baseAddress)
void PMM_SvsLEnabledInLPMFastWake (unsigned int baseAddress)
void PMM_SvsLEnabledInLPMSlowWake (unsigned int baseAddress)
void PMM_SvsLDisabledInLPMFastWake (unsigned int baseAddress)
void PMM_SvsLDisabledInLPMSlowWake (unsigned int baseAddress)
void PMM_SvsHEnabledInLPMNormPerf (unsigned int baseAddress)
void PMM_SvsHEnabledInLPMFullPerf (unsigned int baseAddress)
void PMM_SvsHDisabledInLPMNormPerf (unsigned int baseAddress)
void PMM_SvsHDisabledInLPMFullPerf (unsigned int baseAddress)
void PMM_SvsLOptimizedInLPMFastWake (unsigned int baseAddress)
void PMM_SvsHOptimizedInLPMFullPerf (unsigned int baseAddress)
unsigned int PMM_setVCoreUp (unsigned int baseAddress, unsigned char level)
unsigned int PMM_setVCoreDown (unsigned int baseAddress, unsigned char level)
unsigned short PMM_setVCore (unsigned int baseAddress, unsigned char level)
unsigned int PMM_getInterruptStatus (unsigned int baseAddress, unsigned int mask)
Function Documentation
void PMM_enableSvsL (unsigned int baseAddress)
Enables the low-side SVS circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_disableSvsL (unsigned int baseAddress)
Disables the low-side SVS circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_enableSvmL (unsigned int baseAddress)
Enables the low-side SVM circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_disableSvmL (unsigned int baseAddress)
Disables the low-side SVM circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_enableSvsH (unsigned int baseAddress)
Enables the high-side SVS circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMHCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_disableSvsH (unsigned int baseAddress)
Disables the high-side SVS circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMHCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_enableSvmH (unsigned int baseAddress)
Enables the high-side SVM circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMHCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_disableSvmH (unsigned int baseAddress)
Disables the high-side SVM circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMHCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_enableSvsLSvmL (unsigned int baseAddress)
Enables the low-side SVS and SVM circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_disableSvsLSvmL (unsigned int baseAddress)
Disables the low-side SVS and SVM circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_enableSvsHSvmH (unsigned int baseAddress)
Enables the high-side SVS and SVM circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMHCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_disableSvsHSvmH (unsigned int baseAddress)
Disables the high-side SVS and SVM circuitry
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMHCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_enableSvsLReset (unsigned int baseAddress)
Enables the POR signal generation when a low-voltage event is registered by the low-side SVS
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, PMMRIE.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_disableSvsLReset (unsigned int baseAddress)
Disables the POR signal generation when a low-voltage event is registered by the low-side SVS
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, PMMRIE.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_enableSvmLInterrupt (unsigned int baseAddress)
Enables the interrupt generation when a low-voltage event is registered by the low-side SVM
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, PMMRIE.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_disableSvmLInterrupt (unsigned int baseAddress)
Disables the interrupt generation when a low-voltage event is registered by the low-side SVM
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, PMMRIE.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_enableSvsHReset (unsigned int baseAddress)
Enables the POR signal generation when a low-voltage event is registered by the high-side SVS
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, PMMRIE.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_disableSvsHReset (unsigned int baseAddress)
Disables the POR signal generation when a low-voltage event is registered by the high-side SVS
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, PMMRIE.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_enableSvmHInterrupt (unsigned int baseAddress)
Enables the interrupt generation when a low-voltage event is registered by the high-side SVM
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, PMMRIE.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_disableSvmHInterrupt (unsigned int baseAddress)
Disables the interrupt generation when a low-voltage event is registered by the high-side SVM
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, PMMRIE.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_clearPMMIFGS (unsigned int baseAddress)
Clear all interrupt flags for the PMM
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, PMMIFG.
Returns:
NONE
References HWREGB.
void PMM_SvsLEnabledInLPMFastWake (unsigned int baseAddress)
Enables supervisor low side in LPM with twake-up-fast from LPM2, LPM3, and LPM4
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_SvsLEnabledInLPMSlowWake (unsigned int baseAddress)
Enables supervisor low side in LPM with twake-up-slow from LPM2, LPM3, and LPM4
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_SvsLDisabledInLPMFastWake (unsigned int baseAddress)
Disables supervisor low side in LPM with twake-up-fast from LPM2, LPM3, and LPM4
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_SvsLDisabledInLPMSlowWake (unsigned int baseAddress)
Disables supervisor low side in LPM with twake-up-slow from LPM2, LPM3, and LPM4
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_SvsHEnabledInLPMNormPerf (unsigned int baseAddress)
Enables supervisor high side in LPM with tpd = 20 탎(1)
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMHCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_SvsHEnabledInLPMFullPerf (unsigned int baseAddress)
Enables supervisor high side in LPM with tpd = 2.5 탎(1)
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMHCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_SvsHDisabledInLPMNormPerf (unsigned int baseAddress)
Disables supervisor high side in LPM with tpd = 20 탎(1)
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMHCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_SvsHDisabledInLPMFullPerf (unsigned int baseAddress)
Disables supervisor high side in LPM with tpd = 2.5 탎(1)
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMHCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_SvsLOptimizedInLPMFastWake (unsigned int baseAddress)
Optimized to provide twake-up-fast from LPM2, LPM3, and LPM4 with least power
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
void PMM_SvsHOptimizedInLPMFullPerf (unsigned int baseAddress)
Optimized to provide tpd = 2.5 탎(1) in LPM with least power
Parameters:
baseAddress is the base address of the PMM module.
Modified registers are PMMCTL0, SVSMLCTL.
Returns:
NONE
References HWREG, and HWREGB.
unsigned int PMM_setVCoreUp (unsigned int baseAddress, unsigned char level)
Increase Vcore by one level
Parameters:
baseAddress is the base address of the I2C module.
level level to which Vcore needs to be increased
Modified registers are PMMCTL0, PMMRIE, PMMIFG, SVSMLCTL, SVSMHCTL.
Returns:
STATUS_SUCCESS or STATUS_FAIL
References HWREGB, STATUS_FAIL, and STATUS_SUCCESS.
Referenced by PMM_setVCore().
unsigned int PMM_setVCoreDown (unsigned int baseAddress, unsigned char level)
Decrease Vcore by one level
Parameters:
baseAddress is the base address of the I2C module.
level level to which Vcore needs to be decreased
Modified registers are PMMCTL0, PMMRIE, PMMIFG, SVSMLCTL, SVSMHCTL.
Returns:
STATUS_SUCCESS
References HWREGB, and STATUS_SUCCESS.
Referenced by PMM_setVCore().
unsigned short PMM_setVCore (unsigned int baseAddress, unsigned char level)
Set Vcore to expected level
Parameters:
baseAddress is the base address of the I2C module.
level level to which Vcore needs to be decreased/increased Valid values are PMM_CORE_LEVEL_0 [Default Value], PMM_CORE_LEVEL_1 PMM_CORE_LEVEL_2 PMM_CORE_LEVEL_3
Modified registers are PMMCTL0, PMMRIE, PMMIFG, SVSMLCTL, SVSMHCTL.
Returns:
STATUS_SUCCESS or STATUS_FAIL
References ASSERT, HWREGB, PMM_CORE_LEVEL_0, PMM_CORE_LEVEL_1, PMM_CORE_LEVEL_2, PMM_CORE_LEVEL_3, PMM_setVCoreDown(), PMM_setVCoreUp(), and STATUS_SUCCESS.
unsigned int PMM_getInterruptStatus (unsigned int baseAddress, unsigned int mask)
Returns interrupt status
Parameters:
baseAddress is the base address of the I2C module.
mask is the mask for specifying the required flag Valid values are PMM_SVSMLDLYIFG PMM_SVMLIFG, PMM_SVMLVLRIFG, PMM_SVSMHDLYIFG, PMM_SVMHIFG, PMM_SVMHVLRIFG, PMM_PMMBORIFG, PMM_PMMRSTIFG, PMM_PMMPORIFG, PMM_SVSHIFG, PMM_SVSLIFG, PMM_PMMLPM5IFG
Returns:
STATUS_SUCCESS or STATUS_FAIL
References HWREG.
Copyright 2011, Texas Instruments Incorporated