MSP430 Peripheral Driver Library: timer.c File Reference
timer.c File Reference
#include "inc/hw_types.h"
#include "driverlib/5xx_6xx/debug.h"
#include "driverlib/5xx_6xx/timer.h"
#include "msp430xgeneric.h"
Functions
void privateTimerProcessClockSourceDivider (unsigned int baseAddress, unsigned int clockSourceDivider)
void Timer_startContinousMode (unsigned int baseAddress, unsigned int clockSource, unsigned int clockSourceDivider, unsigned int timerInterruptEnable_TAIE, unsigned int timerclear)
void Timer_startUpMode (unsigned int baseAddress, unsigned int clockSource, unsigned int clockSourceDivider, unsigned int timerPeriod, unsigned int timerInterruptEnable_TAIE, unsigned int captureCompareInterruptEnable_CCR0_CCIE, unsigned int timerclear)
void Timer_startUpDownMode (unsigned int baseAddress, unsigned int clockSource, unsigned int clockSourceDivider, unsigned int timerPeriod, unsigned int timerInterruptEnable_TAIE, unsigned int captureCompareInterruptEnable_CCR0_CCIE, unsigned int timerclear)
void Timer_initCapture (unsigned int baseAddress, unsigned int captureRegister, unsigned int captureMode, unsigned int captureInputSelect, unsigned short synchronizeCaptureSource, unsigned short captureInterruptEnable, unsigned int captureOutputMode)
void Timer_initCompare (unsigned int baseAddress, unsigned int compareRegister, unsigned short compareInterruptEnable, unsigned int compareOutputMode, unsigned int compareValue)
void Timer_enableInterrupt (unsigned int baseAddress)
void Timer_disableInterrupt (unsigned int baseAddress)
unsigned long Timer_getInterruptStatus (unsigned int baseAddress)
void Timer_enableCaptureCompareInterrupt (unsigned int baseAddress, unsigned int captureCompareRegister)
void Timer_disableCaptureCompareInterrupt (unsigned int baseAddress, unsigned int captureCompareRegister)
unsigned long Timer_getCaptureCompareInterruptStatus (unsigned int baseAddress, unsigned int mask)
void Timer_clear (unsigned int baseAddress)
unsigned short Timer_getSynchronizedCaptureCompareInput (unsigned int baseAddress, unsigned int captureCompareRegister, unsigned short synchronized)
unsigned char Timer_getOutputForOutputModeOutBitValue (unsigned int baseAddress, unsigned int captureCompareRegister)
unsigned int Timer_getCaptureCompareCount (unsigned int baseAddress, unsigned int captureCompareRegister)
void Timer_setOutputForOutputModeOutBitValue (unsigned int baseAddress, unsigned int captureCompareRegister, unsigned char outputModeOutBitValue)
void Timer_generatePWM (unsigned int baseAddress, unsigned int clockSource, unsigned int clockSourceDivider, unsigned int timerPeriod, unsigned int compareRegister, unsigned int compareOutputMode, unsigned int dutyCycle)
void Timer_stop (unsigned int baseAddress)
void Timer_setCompareValue (unsigned int baseAddress, unsigned int compareRegister, unsigned int compareValue)
void Timer_clearTimerInterruptFlag (unsigned int baseAddress)
void Timer_clearCaptureCompareInterruptFlag (unsigned int baseAddress, unsigned int captureCompareRegister)
Function Documentation
void privateTimerProcessClockSourceDivider (unsigned int baseAddress, unsigned int clockSourceDivider)
Private clock source divider helper function
Parameters:
baseAddress is the base address of the Timer module.
clockSourceDivider is the desired divider for the clock source
Modified registers are TAxEX0, TAxCTL
Returns:
NONE
References HWREG, TIMER_CLOCKSOURCE_DIVIDER_1, TIMER_CLOCKSOURCE_DIVIDER_10, TIMER_CLOCKSOURCE_DIVIDER_12, TIMER_CLOCKSOURCE_DIVIDER_14, TIMER_CLOCKSOURCE_DIVIDER_16, TIMER_CLOCKSOURCE_DIVIDER_2, TIMER_CLOCKSOURCE_DIVIDER_20, TIMER_CLOCKSOURCE_DIVIDER_24, TIMER_CLOCKSOURCE_DIVIDER_28, TIMER_CLOCKSOURCE_DIVIDER_3, TIMER_CLOCKSOURCE_DIVIDER_32, TIMER_CLOCKSOURCE_DIVIDER_4, TIMER_CLOCKSOURCE_DIVIDER_40, TIMER_CLOCKSOURCE_DIVIDER_48, TIMER_CLOCKSOURCE_DIVIDER_5, TIMER_CLOCKSOURCE_DIVIDER_56, TIMER_CLOCKSOURCE_DIVIDER_6, TIMER_CLOCKSOURCE_DIVIDER_64, TIMER_CLOCKSOURCE_DIVIDER_7, and TIMER_CLOCKSOURCE_DIVIDER_8.
Referenced by Timer_generatePWM(), Timer_startContinousMode(), Timer_startUpDownMode(), and Timer_startUpMode().
void Timer_startContinousMode (unsigned int baseAddress, unsigned int clockSource, unsigned int clockSourceDivider, unsigned int timerInterruptEnable_TAIE, unsigned int timerclear)
Starts timer in continuous mode.
Parameters:
baseAddress is the base address of the Timer module.
clockSource selects Clock source. Valid values are TIMER_CLOCKSOURCE_EXTERNAL_TXCLK [Default value] TIMER_CLOCKSOURCE_ACLK TIMER_CLOCKSOURCE_SMCLK TIMER_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are TIMER_CLOCKSOURCE_DIVIDER_1 [Default value] TIMER_CLOCKSOURCE_DIVIDER_2 TIMER_CLOCKSOURCE_DIVIDER_4 TIMER_CLOCKSOURCE_DIVIDER_8 TIMER_CLOCKSOURCE_DIVIDER_3 TIMER_CLOCKSOURCE_DIVIDER_5 TIMER_CLOCKSOURCE_DIVIDER_6 TIMER_CLOCKSOURCE_DIVIDER_7 TIMER_CLOCKSOURCE_DIVIDER_10 TIMER_CLOCKSOURCE_DIVIDER_12 TIMER_CLOCKSOURCE_DIVIDER_14 TIMER_CLOCKSOURCE_DIVIDER_16 TIMER_CLOCKSOURCE_DIVIDER_20 TIMER_CLOCKSOURCE_DIVIDER_24 TIMER_CLOCKSOURCE_DIVIDER_28 TIMER_CLOCKSOURCE_DIVIDER_32 TIMER_CLOCKSOURCE_DIVIDER_40 TIMER_CLOCKSOURCE_DIVIDER_48 TIMER_CLOCKSOURCE_DIVIDER_56 TIMER_CLOCKSOURCE_DIVIDER_64
timerInterruptEnable_TAIE is to enable or disable timer interrupt Valid values are TIMER_TAIE_INTERRUPT_ENABLE TIMER_TAIE_INTERRUPT_DISABLE [Default value]
timerclear decides if timer clock divider, count direction, count need to be reset. Valid values are TIMER_DO_CLEAR TIMER_SKIP_CLEAR [Default value]
Modified reister is TAxCTL
Returns:
NONE
References ASSERT, HWREG, privateTimerProcessClockSourceDivider(), TIMER_CLOCKSOURCE_ACLK, TIMER_CLOCKSOURCE_DIVIDER_1, TIMER_CLOCKSOURCE_DIVIDER_10, TIMER_CLOCKSOURCE_DIVIDER_12, TIMER_CLOCKSOURCE_DIVIDER_14, TIMER_CLOCKSOURCE_DIVIDER_16, TIMER_CLOCKSOURCE_DIVIDER_2, TIMER_CLOCKSOURCE_DIVIDER_20, TIMER_CLOCKSOURCE_DIVIDER_24, TIMER_CLOCKSOURCE_DIVIDER_28, TIMER_CLOCKSOURCE_DIVIDER_3, TIMER_CLOCKSOURCE_DIVIDER_32, TIMER_CLOCKSOURCE_DIVIDER_4, TIMER_CLOCKSOURCE_DIVIDER_40, TIMER_CLOCKSOURCE_DIVIDER_48, TIMER_CLOCKSOURCE_DIVIDER_5, TIMER_CLOCKSOURCE_DIVIDER_56, TIMER_CLOCKSOURCE_DIVIDER_6, TIMER_CLOCKSOURCE_DIVIDER_64, TIMER_CLOCKSOURCE_DIVIDER_7, TIMER_CLOCKSOURCE_DIVIDER_8, TIMER_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_CLOCKSOURCE_SMCLK, TIMER_CONTINUOUS_MODE, TIMER_DO_CLEAR, TIMER_SKIP_CLEAR, TIMER_TAIE_INTERRUPT_DISABLE, TIMER_TAIE_INTERRUPT_ENABLE, and TIMER_UPDOWN_MODE.
void Timer_startUpMode (unsigned int baseAddress, unsigned int clockSource, unsigned int clockSourceDivider, unsigned int timerPeriod, unsigned int timerInterruptEnable_TAIE, unsigned int captureCompareInterruptEnable_CCR0_CCIE, unsigned int timerclear)
Starts timer in up mode.
Parameters:
baseAddress is the base address of the Timer module.
clockSource selects Clock source. Valid values are TIMER_CLOCKSOURCE_EXTERNAL_TXCLK [Default value] TIMER_CLOCKSOURCE_ACLK TIMER_CLOCKSOURCE_SMCLK TIMER_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are TIMER_CLOCKSOURCE_DIVIDER_1 [Default value] TIMER_CLOCKSOURCE_DIVIDER_2 TIMER_CLOCKSOURCE_DIVIDER_4 TIMER_CLOCKSOURCE_DIVIDER_8 TIMER_CLOCKSOURCE_DIVIDER_3 TIMER_CLOCKSOURCE_DIVIDER_5 TIMER_CLOCKSOURCE_DIVIDER_6 TIMER_CLOCKSOURCE_DIVIDER_7 TIMER_CLOCKSOURCE_DIVIDER_10 TIMER_CLOCKSOURCE_DIVIDER_12 TIMER_CLOCKSOURCE_DIVIDER_14 TIMER_CLOCKSOURCE_DIVIDER_16 TIMER_CLOCKSOURCE_DIVIDER_20 TIMER_CLOCKSOURCE_DIVIDER_24 TIMER_CLOCKSOURCE_DIVIDER_28 TIMER_CLOCKSOURCE_DIVIDER_32 TIMER_CLOCKSOURCE_DIVIDER_40 TIMER_CLOCKSOURCE_DIVIDER_48 TIMER_CLOCKSOURCE_DIVIDER_56 TIMER_CLOCKSOURCE_DIVIDER_64
timerPeriod is the specified timer period
timerInterruptEnable_TAIE is to enable or disable timer interrupt Valid values are TIMER_TAIE_INTERRUPT_ENABLE and TIMER_TAIE_INTERRUPT_DISABLE [Default value]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable timer CCR0 captureComapre interrupt. Valid values are TIMER_CCIE_CCR0_INTERRUPT_ENABLE and TIMER_CCIE_CCR0_INTERRUPT_DISABLE [Default value]
timerclear decides if timer clock divider, count direction, count need to be reset. Valid values are TIMER_DO_CLEAR TIMER_SKIP_CLEAR [Default value]
Modified registers are TAxCTL, TAxCCR0, TAxCCTL0
Returns:
NONE
References ASSERT, HWREG, privateTimerProcessClockSourceDivider(), TIMER_CCIE_CCR0_INTERRUPT_ENABLE, TIMER_CLOCKSOURCE_ACLK, TIMER_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_CLOCKSOURCE_SMCLK, TIMER_DO_CLEAR, TIMER_SKIP_CLEAR, TIMER_TAIE_INTERRUPT_ENABLE, TIMER_UP_MODE, and TIMER_UPDOWN_MODE.
void Timer_startUpDownMode (unsigned int baseAddress, unsigned int clockSource, unsigned int clockSourceDivider, unsigned int timerPeriod, unsigned int timerInterruptEnable_TAIE, unsigned int captureCompareInterruptEnable_CCR0_CCIE, unsigned int timerclear)
Starts timer in up down mode.
Parameters:
baseAddress is the base address of the Timer module.
clockSource selects Clock source. Valid values are TIMER_CLOCKSOURCE_EXTERNAL_TXCLK [Default value] TIMER_CLOCKSOURCE_ACLK TIMER_CLOCKSOURCE_SMCLK TIMER_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are TIMER_CLOCKSOURCE_DIVIDER_1 [Default value] TIMER_CLOCKSOURCE_DIVIDER_2 TIMER_CLOCKSOURCE_DIVIDER_4 TIMER_CLOCKSOURCE_DIVIDER_8 TIMER_CLOCKSOURCE_DIVIDER_3 TIMER_CLOCKSOURCE_DIVIDER_5 TIMER_CLOCKSOURCE_DIVIDER_6 TIMER_CLOCKSOURCE_DIVIDER_7 TIMER_CLOCKSOURCE_DIVIDER_10 TIMER_CLOCKSOURCE_DIVIDER_12 TIMER_CLOCKSOURCE_DIVIDER_14 TIMER_CLOCKSOURCE_DIVIDER_16 TIMER_CLOCKSOURCE_DIVIDER_20 TIMER_CLOCKSOURCE_DIVIDER_24 TIMER_CLOCKSOURCE_DIVIDER_28 TIMER_CLOCKSOURCE_DIVIDER_32 TIMER_CLOCKSOURCE_DIVIDER_40 TIMER_CLOCKSOURCE_DIVIDER_48 TIMER_CLOCKSOURCE_DIVIDER_56 TIMER_CLOCKSOURCE_DIVIDER_64
timerPeriod is the specified timer period
timerInterruptEnable_TAIE is to enable or disable timer interrupt Valid values are TIMER_TAIE_INTERRUPT_ENABLE TIMER_TAIE_INTERRUPT_DISABLE [Default value]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable timer CCR0 captureComapre interrupt. Valid values are TIMER_CCIE_CCR0_INTERRUPT_ENABLE and TIMER_CCIE_CCR0_INTERRUPT_DISABLE [Default value]
timerclear decides if timer clock divider, count direction, count need to be reset. Valid values are TIMER_DO_CLEAR TIMER_SKIP_CLEAR [Default value]
Modified registers are TAxCTL, TAxCCR0, TAxCCTL0
Returns:
NONE
References ASSERT, HWREG, privateTimerProcessClockSourceDivider(), TIMER_CCIE_CCR0_INTERRUPT_ENABLE, TIMER_CLOCKSOURCE_ACLK, TIMER_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_CLOCKSOURCE_SMCLK, TIMER_DO_CLEAR, TIMER_SKIP_CLEAR, TIMER_TAIE_INTERRUPT_ENABLE, and TIMER_UPDOWN_MODE.
void Timer_initCapture (unsigned int baseAddress, unsigned int captureRegister, unsigned int captureMode, unsigned int captureInputSelect, unsigned short synchronizeCaptureSource, unsigned short captureInterruptEnable, unsigned int captureOutputMode)
Initializes Capture Mode
Parameters:
baseAddress is the base address of the Timer module.
captureRegister selects the Capture register being used. Valid values are TIMER_CAPTURECOMPARE_REGISTER_0 TIMER_CAPTURECOMPARE_REGISTER_1 TIMER_CAPTURECOMPARE_REGISTER_2 TIMER_CAPTURECOMPARE_REGISTER_3 TIMER_CAPTURECOMPARE_REGISTER_4 TIMER_CAPTURECOMPARE_REGISTER_5 TIMER_CAPTURECOMPARE_REGISTER_6 Refer datasheet to ensure the device has the capture compare register being used
captureMode is the capture mode selected. Valid values are TIMER_CAPTUREMODE_NO_CAPTURE [Default value] TIMER_CAPTUREMODE_RISING_EDGE TIMER_CAPTUREMODE_FALLING_EDGE TIMER_CAPTUREMODE_RISING_AND_FALLING_EDGE
captureInputSelect decides the Input Select TIMER_CAPTURE_INPUTSELECT_CCIxA [Default value] TIMER_CAPTURE_INPUTSELECT_CCIxB TIMER_CAPTURE_INPUTSELECT_GND TIMER_CAPTURE_INPUTSELECT_Vcc
synchronizeCaptureSource decides if capture source should be synchronized with timer clock Valid values are TIMER_CAPTURE_ASYNCHRONOUS [Default value] TIMER_CAPTURE_SYNCHRONOUS
captureInterruptEnable is to enable or disable timer captureComapre interrupt. Valid values are TIMER_CAPTURECOMPARE_INTERRUPT_DISABLE [Default value] TIMER_CAPTURECOMPARE_INTERRUPT_ENABLE
captureOutputMode specifies the ouput mode. Valid values are TIMER_OUTPUTMODE_OUTBITVALUE [Default value], TIMER_OUTPUTMODE_SET, TIMER_OUTPUTMODE_TOGGLE_RESET, TIMER_OUTPUTMODE_SET_RESET TIMER_OUTPUTMODE_TOGGLE, TIMER_OUTPUTMODE_RESET, TIMER_OUTPUTMODE_TOGGLE_SET, TIMER_OUTPUTMODE_RESET_SET
Modified register is TAxCCTLn
Returns:
NONE
References ASSERT, HWREG, TIMER_CAPTURE_ASYNCHRONOUS, TIMER_CAPTURE_INPUTSELECT_CCIxA, TIMER_CAPTURE_INPUTSELECT_CCIxB, TIMER_CAPTURE_INPUTSELECT_GND, TIMER_CAPTURE_INPUTSELECT_Vcc, TIMER_CAPTURE_SYNCHRONOUS, TIMER_CAPTURECOMPARE_INTERRUPT_DISABLE, TIMER_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, TIMER_CAPTURECOMPARE_REGISTER_6, TIMER_CAPTUREMODE_FALLING_EDGE, TIMER_CAPTUREMODE_NO_CAPTURE, TIMER_CAPTUREMODE_RISING_AND_FALLING_EDGE, TIMER_CAPTUREMODE_RISING_EDGE, TIMER_DO_CLEAR, TIMER_OUTPUTMODE_OUTBITVALUE, TIMER_OUTPUTMODE_RESET, TIMER_OUTPUTMODE_RESET_SET, TIMER_OUTPUTMODE_SET, TIMER_OUTPUTMODE_SET_RESET, TIMER_OUTPUTMODE_TOGGLE, TIMER_OUTPUTMODE_TOGGLE_RESET, TIMER_OUTPUTMODE_TOGGLE_SET, and TIMER_TAIE_INTERRUPT_ENABLE.
void Timer_initCompare (unsigned int baseAddress, unsigned int compareRegister, unsigned short compareInterruptEnable, unsigned int compareOutputMode, unsigned int compareValue)
Initializes Compare Mode
Parameters:
baseAddress is the base address of the Timer module.
captureRegister selects the Capture register being used. Valid values are TIMER_CAPTURECOMPARE_REGISTER_0 TIMER_CAPTURECOMPARE_REGISTER_1 TIMER_CAPTURECOMPARE_REGISTER_2 TIMER_CAPTURECOMPARE_REGISTER_3 TIMER_CAPTURECOMPARE_REGISTER_4 TIMER_CAPTURECOMPARE_REGISTER_5 TIMER_CAPTURECOMPARE_REGISTER_6 Refer datasheet to ensure the device has the capture compare register being used
compareInterruptEnable is to enable or disable timer captureComapre interrupt. Valid values are TIMER_CAPTURECOMPARE_INTERRUPT_ENABLE and TIMER_CAPTURECOMPARE_INTERRUPT_DISABLE [Default value]
compareOutputMode specifies the ouput mode. Valid values are TIMER_OUTPUTMODE_OUTBITVALUE [Default value], TIMER_OUTPUTMODE_SET, TIMER_OUTPUTMODE_TOGGLE_RESET, TIMER_OUTPUTMODE_SET_RESET TIMER_OUTPUTMODE_TOGGLE, TIMER_OUTPUTMODE_RESET, TIMER_OUTPUTMODE_TOGGLE_SET, TIMER_OUTPUTMODE_RESET_SET
compareValue is the count to be compared with in compare mode
Modified register is TAxCCTLn and TAxCCRn
Returns:
NONE
References ASSERT, HWREG, TIMER_CAPTURECOMPARE_INTERRUPT_DISABLE, TIMER_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, TIMER_CAPTURECOMPARE_REGISTER_6, TIMER_OUTPUTMODE_OUTBITVALUE, TIMER_OUTPUTMODE_RESET, TIMER_OUTPUTMODE_RESET_SET, TIMER_OUTPUTMODE_SET, TIMER_OUTPUTMODE_SET_RESET, TIMER_OUTPUTMODE_TOGGLE, TIMER_OUTPUTMODE_TOGGLE_RESET, and TIMER_OUTPUTMODE_TOGGLE_SET.
void Timer_enableInterrupt (unsigned int baseAddress)
Enable timer interrupt
Parameters:
baseAddress is the base address of the Timer module.
Modified register is TAxCTL
Returns:
NONE
References HWREG, and HWREGB.
void Timer_disableInterrupt (unsigned int baseAddress)
Disable timer interrupt
Parameters:
baseAddress is the base address of the Timer module.
Modified register is TAxCTL
Returns:
NONE
References HWREG.
unsigned long Timer_getInterruptStatus (unsigned int baseAddress)
Get timer interrupt status
Parameters:
baseAddress is the base address of the Timer module.
Returns:
unsigned long. Return interrupt status. Valid values are TIMER_INTERRUPT_PENDING TIMER_INTERRUPT_NOT_PENDING
References HWREG.
void Timer_enableCaptureCompareInterrupt (unsigned int baseAddress, unsigned int captureCompareRegister)
Enable capture compare interrupt
Parameters:
baseAddress is the base address of the Timer module.
captureCompareRegister is the selected capture compare regsiter
Modified register is TAxCCTLn
Returns:
NONE
References ASSERT, HWREG, HWREGB, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, and TIMER_CAPTURECOMPARE_REGISTER_6.
void Timer_disableCaptureCompareInterrupt (unsigned int baseAddress, unsigned int captureCompareRegister)
Disable capture compare interrupt
Parameters:
baseAddress is the base address of the Timer module.
captureCompareRegister is the selected capture compare regsiter
Modified register is TAxCCTLn
Returns:
NONE
References ASSERT, HWREG, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, and TIMER_CAPTURECOMPARE_REGISTER_6.
unsigned long Timer_getCaptureCompareInterruptStatus (unsigned int baseAddress, unsigned int mask)
Return capture compare interrupt status
Parameters:
baseAddress is the base address of the Timer module.
mask is the mask for the interrupt status Valid values is and OR of TIMER_CAPTURE_OVERFLOW, TIMER_CAPTURECOMPARE_INTERRUPT_FLAG
Modified register is TAxCTL
Returns:
unsigned long. The mask of the set flags.
References HWREG.
void Timer_clear (unsigned int baseAddress)
Reset/Clear the timer clock divider, count direction, count
Parameters:
baseAddress is the base address of the Timer module.
Modified register is TAxCTL
Returns:
NONE
References HWREG.
unsigned short Timer_getSynchronizedCaptureCompareInput (unsigned int baseAddress, unsigned int captureCompareRegister, unsigned short synchronized)
Get synchrnozied capturecompare input
Parameters:
baseAddress is the base address of the Timer module.
captureRegister selects the Capture register being used. Valid values are TIMER_CAPTURECOMPARE_REGISTER_0 TIMER_CAPTURECOMPARE_REGISTER_1 TIMER_CAPTURECOMPARE_REGISTER_2 TIMER_CAPTURECOMPARE_REGISTER_3 TIMER_CAPTURECOMPARE_REGISTER_4 TIMER_CAPTURECOMPARE_REGISTER_5 TIMER_CAPTURECOMPARE_REGISTER_6 Refer datasheet to ensure the device has the capture compare register being used
synchronized is to select type of capture compare input. Valid values are TIMER_READ_CAPTURE_COMPARE_INPUT TIMER_READ_SYNCHRONIZED_CAPTURECOMPAREINPUT
Returns:
TIMER_CAPTURECOMPARE_INPUT_HIGH or TIMER_CAPTURECOMPARE_INPUT_LOW
References ASSERT, HWREG, TIMER_CAPTURECOMPARE_INPUT_HIGH, TIMER_CAPTURECOMPARE_INPUT_LOW, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, TIMER_CAPTURECOMPARE_REGISTER_6, TIMER_READ_CAPTURE_COMPARE_INPUT, and TIMER_READ_SYNCHRONIZED_CAPTURECOMPAREINPUT.
unsigned char Timer_getOutputForOutputModeOutBitValue (unsigned int baseAddress, unsigned int captureCompareRegister)
Get ouput bit for output mode
Parameters:
baseAddress is the base address of the Timer module.
captureRegister selects the Capture register being used. Valid values are TIMER_CAPTURECOMPARE_REGISTER_0 TIMER_CAPTURECOMPARE_REGISTER_1 TIMER_CAPTURECOMPARE_REGISTER_2 TIMER_CAPTURECOMPARE_REGISTER_3 TIMER_CAPTURECOMPARE_REGISTER_4 TIMER_CAPTURECOMPARE_REGISTER_5 TIMER_CAPTURECOMPARE_REGISTER_6 Refer datasheet to ensure the device has the capture compare register being used
Returns:
TIMER_OUTPUTMODE_OUTBITVALUE_HIGH or TIMER_OUTPUTMODE_OUTBITVALUE_LOW
References ASSERT, HWREG, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, TIMER_CAPTURECOMPARE_REGISTER_6, TIMER_OUTPUTMODE_OUTBITVALUE_HIGH, and TIMER_OUTPUTMODE_OUTBITVALUE_LOW.
unsigned int Timer_getCaptureCompareCount (unsigned int baseAddress, unsigned int captureCompareRegister)
Get current capturecompare count
Parameters:
baseAddress is the base address of the Timer module.
captureRegister selects the Capture register being used. Valid values are TIMER_CAPTURECOMPARE_REGISTER_0 TIMER_CAPTURECOMPARE_REGISTER_1 TIMER_CAPTURECOMPARE_REGISTER_2 TIMER_CAPTURECOMPARE_REGISTER_3 TIMER_CAPTURECOMPARE_REGISTER_4 TIMER_CAPTURECOMPARE_REGISTER_5 TIMER_CAPTURECOMPARE_REGISTER_6 Refer datasheet to ensure the device has the capture compare register being used
Returns:
current count as unsigned int
References ASSERT, HWREG, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, and TIMER_CAPTURECOMPARE_REGISTER_6.
void Timer_setOutputForOutputModeOutBitValue (unsigned int baseAddress, unsigned int captureCompareRegister, unsigned char outputModeOutBitValue)
Set ouput bit for output mode
Parameters:
baseAddress is the base address of the Timer module.
captureRegister selects the Capture register being used. Valid values are TIMER_CAPTURECOMPARE_REGISTER_0 TIMER_CAPTURECOMPARE_REGISTER_1 TIMER_CAPTURECOMPARE_REGISTER_2 TIMER_CAPTURECOMPARE_REGISTER_3 TIMER_CAPTURECOMPARE_REGISTER_4 TIMER_CAPTURECOMPARE_REGISTER_5 TIMER_CAPTURECOMPARE_REGISTER_6 Refer datasheet to ensure the device has the capture compare register being used
outputModeOutBitValueis the value to be set for out bit Valid values are TIMER_OUTPUTMODE_OUTBITVALUE_HIGH TIMER_OUTPUTMODE_OUTBITVALUE_LOW
Modified register is TAxCCTLn
Returns:
NONE
References ASSERT, HWREG, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, TIMER_CAPTURECOMPARE_REGISTER_6, TIMER_OUTPUTMODE_OUTBITVALUE_HIGH, and TIMER_OUTPUTMODE_OUTBITVALUE_LOW.
void Timer_generatePWM (unsigned int baseAddress, unsigned int clockSource, unsigned int clockSourceDivider, unsigned int timerPeriod, unsigned int compareRegister, unsigned int compareOutputMode, unsigned int dutyCycle)
Generate a PWM with timer running in up down mode
Parameters:
baseAddress is the base address of the Timer module.
clockSource selects Clock source. Valid values are TIMER_CLOCKSOURCE_EXTERNAL_TXCLK TIMER_CLOCKSOURCE_ACLK TIMER_CLOCKSOURCE_SMCLK TIMER_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are TIMER_CLOCKSOURCE_DIVIDER_1 TIMER_CLOCKSOURCE_DIVIDER_2 TIMER_CLOCKSOURCE_DIVIDER_4 TIMER_CLOCKSOURCE_DIVIDER_8 TIMER_CLOCKSOURCE_DIVIDER_3 TIMER_CLOCKSOURCE_DIVIDER_5 TIMER_CLOCKSOURCE_DIVIDER_6 TIMER_CLOCKSOURCE_DIVIDER_7 TIMER_CLOCKSOURCE_DIVIDER_10 TIMER_CLOCKSOURCE_DIVIDER_12 TIMER_CLOCKSOURCE_DIVIDER_14 TIMER_CLOCKSOURCE_DIVIDER_16 TIMER_CLOCKSOURCE_DIVIDER_20 TIMER_CLOCKSOURCE_DIVIDER_24 TIMER_CLOCKSOURCE_DIVIDER_28 TIMER_CLOCKSOURCE_DIVIDER_32 TIMER_CLOCKSOURCE_DIVIDER_40 TIMER_CLOCKSOURCE_DIVIDER_48 TIMER_CLOCKSOURCE_DIVIDER_56 TIMER_CLOCKSOURCE_DIVIDER_64
timerPeriod selects the desired timer period
compareRegister selects the compare register being used. Valid values are TIMER_CAPTURECOMPARE_REGISTER_0 TIMER_CAPTURECOMPARE_REGISTER_1 TIMER_CAPTURECOMPARE_REGISTER_2 TIMER_CAPTURECOMPARE_REGISTER_3 TIMER_CAPTURECOMPARE_REGISTER_4 TIMER_CAPTURECOMPARE_REGISTER_5 TIMER_CAPTURECOMPARE_REGISTER_6 Refer datasheet to ensure the device has the capture compare register being used
compareOutputMode specifies the ouput mode. Valid values are TIMER_OUTPUTMODE_OUTBITVALUE, TIMER_OUTPUTMODE_SET, TIMER_OUTPUTMODE_TOGGLE_RESET, TIMER_OUTPUTMODE_SET_RESET TIMER_OUTPUTMODE_TOGGLE, TIMER_OUTPUTMODE_RESET, TIMER_OUTPUTMODE_TOGGLE_SET, TIMER_OUTPUTMODE_RESET_SET
dutyCycle specifies the dutycycle for the generated waveform
Modified registers are TAxCTL, TAxCCR0, TAxCCTL0,TAxCCTLn
Returns:
NONE
References ASSERT, HWREG, privateTimerProcessClockSourceDivider(), TIMER_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, TIMER_CAPTURECOMPARE_REGISTER_6, TIMER_CLOCKSOURCE_ACLK, TIMER_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_CLOCKSOURCE_SMCLK, TIMER_DO_CLEAR, TIMER_OUTPUTMODE_OUTBITVALUE, TIMER_OUTPUTMODE_RESET, TIMER_OUTPUTMODE_RESET_SET, TIMER_OUTPUTMODE_SET, TIMER_OUTPUTMODE_SET_RESET, TIMER_OUTPUTMODE_TOGGLE, TIMER_OUTPUTMODE_TOGGLE_RESET, TIMER_OUTPUTMODE_TOGGLE_SET, TIMER_TAIE_INTERRUPT_ENABLE, TIMER_UP_MODE, and TIMER_UPDOWN_MODE.
void Timer_stop (unsigned int baseAddress)
Stops the timer
Parameters:
baseAddress is the base address of the Timer module.
Modified registers are TAxCTL
Returns:
NONE
References HWREG.
void Timer_setCompareValue (unsigned int baseAddress, unsigned int compareRegister, unsigned int compareValue)
Sets the value of the capture-compare register
Parameters:
baseAddress is the base address of the Timer module.
captureRegister selects the Capture register being used. Valid values are TIMER_CAPTURECOMPARE_REGISTER_0 TIMER_CAPTURECOMPARE_REGISTER_1 TIMER_CAPTURECOMPARE_REGISTER_2 TIMER_CAPTURECOMPARE_REGISTER_3 TIMER_CAPTURECOMPARE_REGISTER_4 TIMER_CAPTURECOMPARE_REGISTER_5 TIMER_CAPTURECOMPARE_REGISTER_6 Refer datasheet to ensure the device has the capture compare register being used
compareValue is the count to be compared with in compare mode
Modified register is TAxCCRn
Returns:
NONE
References ASSERT, HWREG, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, and TIMER_CAPTURECOMPARE_REGISTER_6.
void Timer_clearTimerInterruptFlag (unsigned int baseAddress)
Clears the Timer TAIFG interrupt flag
Parameters:
baseAddress is the base address of the Timer module.
Modified bits are TAIFG og TAxCTL register
Returns:
NONE
References HWREGB.
void Timer_clearCaptureCompareInterruptFlag (unsigned int baseAddress, unsigned int captureCompareRegister)
Clears the capture-compare interrupt flag
Parameters:
baseAddress is the base address of the Timer module.
captureCompareRegister selects the Capture-compare register being used. Valid values are TIMER_CAPTURECOMPARE_REGISTER_0 TIMER_CAPTURECOMPARE_REGISTER_1 TIMER_CAPTURECOMPARE_REGISTER_2 TIMER_CAPTURECOMPARE_REGISTER_3 TIMER_CAPTURECOMPARE_REGISTER_4 TIMER_CAPTURECOMPARE_REGISTER_5 TIMER_CAPTURECOMPARE_REGISTER_6 Refer datasheet to ensure the device has the capture compare register being used
Modified bits are CCIFG of TAxCCTLn register
Returns:
NONE
References ASSERT, HWREG, TIMER_CAPTURECOMPARE_REGISTER_0, TIMER_CAPTURECOMPARE_REGISTER_1, TIMER_CAPTURECOMPARE_REGISTER_2, TIMER_CAPTURECOMPARE_REGISTER_3, TIMER_CAPTURECOMPARE_REGISTER_4, TIMER_CAPTURECOMPARE_REGISTER_5, and TIMER_CAPTURECOMPARE_REGISTER_6.
Copyright 2011, Texas Instruments Incorporated