MSP430 Peripheral Driver Library: uart_baudrate.h File Reference
uart_baudrate.h File Reference
Data Structures
struct ERROR_STRUCTURE
Defines
#define __MSP430_HAS_USCI_Ax__
#define UARTBAUDRATE_LOW_FREQUENCY_BAUDRATE_GENERATION 0x00
Typedefs
typedef struct ERROR_STRUCTURE MAX_ERR
Functions
double UARTBAUDRATE_txTbit (unsigned int mode, unsigned int i, unsigned int s_mod, unsigned int f_mod)
MAX_ERR UARTBAUDRATE_txError (unsigned int mode, unsigned int s_mod, unsigned int f_mod)
MAX_ERR UARTBAUDRATE_rxError (unsigned int mode, unsigned int s_mod, unsigned int f_mod, double t_sync)
unsigned short UARTBAUDRATE_calculateBaudDividers (double brclk_f, double baudrate_f, unsigned char *UCAxBR0_value, unsigned char *UCAxBR1_value, unsigned int *UCAxMCTL_value, unsigned short overSampling)
Define Documentation
#define __MSP430_HAS_USCI_Ax__
#define UARTBAUDRATE_LOW_FREQUENCY_BAUDRATE_GENERATION 0x00
Referenced by UARTBAUDRATE_calculateBaudDividers().
Typedef Documentation
typedef struct ERROR_STRUCTURE MAX_ERR
Function Documentation
double UARTBAUDRATE_txTbit (unsigned int mode, unsigned int i, unsigned int s_mod, unsigned int f_mod)
References baudrate, brclk, lf_div_i, osr_div_i, and UCSx_mod.
Referenced by UARTBAUDRATE_rxError(), and UARTBAUDRATE_txError().
MAX_ERR UARTBAUDRATE_txError (unsigned int mode, unsigned int s_mod, unsigned int f_mod)
References baudrate, ERROR_STRUCTURE::max_error, ERROR_STRUCTURE::max_negative_error, ERROR_STRUCTURE::max_positive_error, NO_BITS, and UARTBAUDRATE_txTbit().
Referenced by UARTBAUDRATE_calculateBaudDividers().
MAX_ERR UARTBAUDRATE_rxError (unsigned int mode, unsigned int s_mod, unsigned int f_mod, double t_sync)
References baudrate, brclk, lf_div_i, ERROR_STRUCTURE::max_error, ERROR_STRUCTURE::max_negative_error, ERROR_STRUCTURE::max_positive_error, NO_BITS, osr_div_i, UARTBAUDRATE_txTbit(), and UCSx_mod.
unsigned short UARTBAUDRATE_calculateBaudDividers (double brclk_f, double baudrate_f, unsigned char * UCAxBR0_value, unsigned char * UCAxBR1_value, unsigned int * UCAxMCTL_value, unsigned short overSampling)
References baudrate, brclk, lf_div_f, lf_div_i, ERROR_STRUCTURE::max_error, ERROR_STRUCTURE::max_negative_error, ERROR_STRUCTURE::max_positive_error, osr_div_f, osr_div_i, STATUS_FAIL, STATUS_SUCCESS, UARTBAUDRATE_LOW_FREQUENCY_BAUDRATE_GENERATION, and UARTBAUDRATE_txError().
Referenced by UART_init().
Copyright 2011, Texas Instruments Incorporated