#!/bin/bash
LIBS="libair libarduino libcomm libcore libfat libhal liblcd libmidi libsound"
OP=""
DEFINED=""
while getopts ":m:vhbra:lcpid:D" opt; do
	case $opt in
		D)
			OP="docs"
			;;
		d)
			DEFINED="$OPTARG"
			;;
		m)
			MCU="$OPTARG"
			;;
		p)
			OP="package"
			;;
		l)
			OP="list"
			;;
		r)
			OP="remove"
			;;
		b)
			OP="build"
			;;
		c)
			OP="clean"
                        echo "-- Will do Clean"
			;;
		a)
			OP="patch"
			PATCH="$OPTARG"
			;;
		i)
			NAME=`dirname $0`
			LIBDIR="${NAME}${MCU}/lib"
			INCDIR="${NAME}${MCU}/include"
			shift
			echo "-L$LIBDIR -I$INCDIR $@"
			exit 0
			;;
		v)
			;;
		h)
			echo "`basename $0` - lib430 Builder"
			echo "(c) 2011-2012, NoccyLabs.info"
			echo
			echo "Usage: `basename $0` [-m <mcu>] [-d <defines>][-v] -b"
			echo "       `basename $0` [-m <mcu>] -r"
			echo "       `basename $0` -l"
			echo "       `basename $0` -c"
			echo "       `basename $0` -a <info-here>"
			echo "       `basename $0` -h"
			echo "       `basename $0` -i"
			echo ""
			echo "  -m  MCU (msp430g2553,...)"
			echo "  -d  Pass on one or more defines, quote the string please"
			echo "  -p  Package module"
			echo "  -r  Remove modules"
			echo "  -l  List modules"
			echo "  -c  Clean modules"
			echo "  -a  Create patch with description"
			echo "  -h  Show this help"
			exit 1
			;;
	esac
done

case "$OP" in
	"patch")
		REV="`svn info | grep -i revision | cut -f 2 -d' '`"
		DEST=./lib430-r$REV-$PATCH-patch.diff
		svn diff > $DEST
		echo "Patch saved to $DEST"
		;;
	"list")
		ls -al | grep msp430*
		;;
	"clean")
		for LIB in $LIBS; do
			echo -n " :: $LIB: "
			cd src/$LIB
			if [ -e Makefile ]; then
				make clean &> /dev/null
			fi
			echo "Clean"
			cd ../..
		done
		;;
	"docs")
		echo "== Cooking docs =="

		for LIB in $LIBS; do
			rm -rf docs/$LIB
			mkdir -p docs
			cd src/$LIB
			if [ -e Doxyfile ]; then
				echo -n "$LIB: "
				make docs &> /dev/null
				echo "Done"
				mv html ../../docs/$LIB
			fi
			cd ../..
		done
		;;
	"build")
		if [ -z "$MCU" ]; then
			echo "No MCU defined. Either export MCU or use -m MCU."
			exit 1
		fi
		echo "== Cooking for: $MCU =="
		if [ ! -z "$CXXFLAGS" ]; then
			echo "   :: CXXFLAGS=$CXXFLAGS"
		fi
		echo "   :: Installing to $MCU/lib"
		rm -rf $MCU
		mkdir -p $MCU/include $MCU/lib
		export MCU

		for LIB in $LIBS; do
			cd src/$LIB
			if [ -e Makefile ]; then
				make clean &> /dev/null
				make lib CXXFLAGS="$CXXFLAGS" &>../../$MCU/$LIB.log
			fi
			if [ "$?" == "0" ]; then
				LIBCOUNT="`ls -al *.a 2>/dev/null | wc -l`"
				HCOUNT="`ls -al *.h 2>/dev/null | wc -l`"
				printf "   %s %-20s |%4s| (%d libraries, %d headers)\n" "··" $LIB " OK " $LIBCOUNT $HCOUNT
				cp $LIB.a ../../$MCU/lib/ &>/dev/null
				cp *.h ../../$MCU/include/ &>/dev/null
			else
				printf "   %s %-20s |%4s| Failed, see %s\n" "  " $LIB "" "$MCU/$LIB.log"
				cat ../../$MCU/$LIB.log | grep -i error > ../../$MCU/$LIB.err
			fi
			cd ../..
		done
		ls $MCU/lib/*.a &>/dev/null && echo "   :: Chmodding libraries..." && chmod 666 $MCU/lib/*.a
		chmod 666 $MCU/include/*.h
		LIBCOUNT="`ls -al $MCU/lib/*.a 2>/dev/null | wc -l`"
		HCOUNT="`ls -al $MCU/include/*.h 2>/dev/null | wc -l`"
		echo "   :: $LIBCOUNT libraries and $HCOUNT headers have been installed."
		;;
	"package")
		if [ ! -d "$MCU" ]; then
			echo "You need to build it first..."
			exit 1
		fi
		tar cvfz lib430-$MCU.tgz $MCU
		;;
	*)
		echo "Try -h"
		;;
esac

