
#define PORT_ALERTLED P1OUT
#define BIT_ALERTLED BIT4
#define PORT_RELAYCTL P1OUT
#define BIT_RELAYCTL BIT5
#define PORT_STATUSLED P1OUT
#define BIT_STATUSLED BIT6

#define PORT_SENSE P1IN
#define BIT_SENSE BIT7
