#!/bin/bash
COMPATIBLE=`mspdebug --fet-list`
for f in /usr/msp430/include/msp*.h; do 
	grep -i $1 $f &> /dev/null
	FOUND=$?
	MCU=`basename $f .h`
	if [ "$FOUND" == "0" ]; then
		echo $COMPATIBLE | grep -i $MCU &> /dev/null
		if [ "$?" == "0" ]; then
			echo -n "OK: "
		else
			echo -n "UNSUP: "
		fi
	else
		echo -n "MISS: "
	fi
	echo "$MCU"
done
