#
# Generic Makefile for MSP430-based projects
#
# (c) 2011, NoccyLabs.info
#
# Source files and target binary, define your source files here to have them
# compiled, and define the target basename. An .elf binary will be created as
# well as a .hex file:
SOURCES  = main.c database.c config.c
SOURCESA =
TARGET   = mspov
INCLUDES = -I../../lib430/include
LIBS     = -L../../lib430/libs

include common.mk
